-- CREATE DATABASE
CREATE DATABASE PLGCOMETRONIC;

DROP TABLE TB_PRODUTO;

-- CREATE TB_PRODUTO
CREATE TABLE TB_PRODUTO(
		CODIGO												INTEGER 						NOT NULL,
		ID_CATEGORIA									INTEGER							NOT NULL,
  	NOME													VARCHAR(255)				NOT NULL,
		DESCRICAO											VARCHAR(255)						NULL,
		URL_IMAGEM										VARCHAR(255)						NULL,
		PRECO													DOUBLE									NULL,
		QUANTIDADE_DISPONIVEL					INTEGER									NULL,
  	DATA_ULTIMA_ALTERACAO					TIMESTAMP								NULL,
  	USUARIO_UTLTIMA_ALTERACAO			VARCHAR(100)					  NULL
);

-- CREATE TABLE
ALTER TABLE TB_PRODUTO MODIFY CODIGO INTEGER AUTO_INCREMENT PRIMARY KEY;

-- INSERT INTO
INSERT INTO TB_PRODUTO(CODIGO, ID_CATEGORIA, NOME, DESCRICAO, URL_IMAGEM, PRECO, QUANTIDADE_DISPONIVEL, DATA_ULTIMA_ALTERACAO, USUARIO_UTLTIMA_ALTERACAO) VALUES(NULL, 1, 'Monitor LED 25'' Gamer LG MBR 25UM58G 2560 x 1080 UltraWide IPS Full HD 1ms', '25” Monitor UltraWide IPS FHD Imagens meramente ilustrativas.Todas as informações divulgadas são de responsabilidade do Fabricante/Fornecedor ...', 'https://images-na.ssl-images-amazon.com/images/I/61-3PV4JQ8L._AC_SY450_.jpg', 1500, 10, NOW(), 'CARGA DE TESTE');

-- SELECT
SELECT * FROM TB_PRODUTO;
